config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static#index'

  resources :saved_searches, :only => %w(index new create destroy)
  resources :hacker_news_stories, :only => %w(index)

  get :search, to: 'hacker_news_stories#search'
  get :my_stories, to: 'hacker_news_stories#my_stories'

  constraints ->(request) { request.env['warden'].authenticate? && request.env['warden'].user.admin? } do
    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  end
end

app/models/hacker_news_story.rb
class HackerNewsStory < ActiveRecord::Base
  validates :hn_id, :story_url, :title, :first_seen_on_front_page_at, presence: true

  scope :recent_first, -> { order(first_seen_on_front_page_at: :desc) }

  class << self
    def scrape
      HackerNews.new.latest_hn_stories.each do |attrs|
        where(hn_id: attrs[:hn_id]).first_or_create! do |s|
          s.first_seen_on_front_page_at = Time.zone.now
          s.attributes = attrs
        end
      end
    end
    handle_asynchronously :scrape, :priority => 1

    private

    def full_text_search(raw_tsquery)
      select("#{table_name}.*, ts_rank_cd(#{table_name}.full_text_search, query) rank").
      from("#{table_name}, #{raw_tsquery} query").
      where("query @@ #{table_name}.full_text_search").
      order('rank desc')
    end
  end

  scope :search, ->(query) do
    full_text_search("plainto_tsquery(#{connection.quote(query)})")
  end

  scope :matching_any_term, ->(terms) do
    ts_query_matching_any_term = terms.map { |t|
      "plainto_tsquery(#{connection.quote(t)})::text"
    }.join(%{ || ' | ' || })

    full_text_search(%{to_tsquery(#{ts_query_matching_any_term})})
  end

  scope :matching_user_saved_searches, ->(user) do
    matching_any_term(user.saved_searches.map(&:query))
  end

  def comments_url
    "https://news.ycombinator.com/item?id=#{hn_id}"
  end
end

app/models/saved_search.rb
class SavedSearch < ActiveRecord::Base
  belongs_to :user
  validates :query, presence: true

  def matching_stories
    HackerNewsStory.search(query)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :saved_searches

  class << self
    def notify_new_stories
      User.find_each do |u|
        stories = u.saved_searches.inject(Set.new) do |set, search|
          matching_stories =
            search.
              matching_stories.
              where('first_seen_on_front_page_at > ?', u.last_notified_of_new_stories_at)

          set += matching_stories.to_a
          set
        end

        if stories.present?
          u.transaction do
            u.update!(last_notified_of_new_stories_at: Time.zone.now)
            HackerNewsStoryMailer.new_stories(u, stories.sort_by(&:title)).deliver
          end
        end
      end
    end
    handle_asynchronously :notify_new_stories, :priority => 2
  end

  def last_notified_of_new_stories_at
    super || Time.at(0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(current_user)
    saved_searches_path
  end

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/hacker_news_stories_controller.rb
class HackerNewsStoriesController < ApplicationController
  before_filter :authenticate_user!

  expose(:query) { params[:q].presence }

  def index
    @hacker_news_stories = stories
  end

  def my_stories
    @hacker_news_stories = stories.matching_user_saved_searches(current_user)
  end

  def search
    @hacker_news_stories = stories.search(query)
  end

  private

  def stories
    HackerNewsStory.recent_first.paginate(:page => params[:page])
  end
end

app/controllers/saved_searches_controller.rb
class SavedSearchesController < ApplicationController
  before_filter :authenticate_user!

  expose(:saved_searches) { current_user.saved_searches }
  expose(:saved_search, attributes: :saved_search_params)

  def index
  end

  def new
  end

  def create
    if saved_search.save
      redirect_to saved_searches_path, notice: 'Search was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    saved_search.destroy
    redirect_to saved_searches_url, notice: 'Search was successfully destroyed.'
  end

  private

  def saved_search_params
    params.require(:saved_search).permit(:query)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_filter { redirect_to(after_sign_in_path_for(current_user)) if user_signed_in? }
end

app/helpers/application_helper.rb
module ApplicationHelper
  def rails_to_bootstrap_flash_key(key)
    {notice: :success, alert: :warning, error: :danger}.with_indifferent_access.fetch(key)
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/hacker_news_stories/_stories.html.haml
%table.table
  %tr
    %th Story
    %th
    %th First Seen on Front Page At

  - stories.each do |hacker_news_story|
    %tr
      %td= link_to hacker_news_story.title, hacker_news_story.story_url, target: '_blank'
      %td= link_to 'Comments', hacker_news_story.comments_url, target: '_blank'
      %td= hacker_news_story.first_seen_on_front_page_at

= will_paginate stories

app/views/hacker_news_stories/index.html.haml
%h1
  - if query
    - if hacker_news_stories.any?
      = "Stories matching #{query.inspect}"
    - else
      No Results
  - else
    All Stories

%table.table
  %tr
    %th Story
    %th
    %th First Seen on Front Page At

  - hacker_news_stories.each do |hacker_news_story|
    %tr
      %td= link_to hacker_news_story.title, hacker_news_story.story_url, target: '_blank'
      %td= link_to 'Comments', hacker_news_story.comments_url, target: '_blank'
      %td= hacker_news_story.first_seen_on_front_page_at

= will_paginate hacker_news_stories

app/views/hacker_news_stories/my_stories.html.haml
%h1 Your Stories

= render 'stories', :stories => @hacker_news_stories

app/views/hacker_news_stories/search.html.haml
%h1
  - if @hacker_news_stories.any?
    = "Stories matching #{query.inspect}"
  - else
    No Results

= render 'stories', :stories => @hacker_news_stories

app/views/layouts/application.html.haml
!!! 5
- application_name = Rails.application.class.to_s.split('::').first
%html(lang="en-US" class="#{controller_name}-#{action_name}")
  %head
    %title
      - if content_for?(:title)
        = yield (:title)
      - else
        = application_name
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
        .container-fluid
          .navbar-header
            %a.navbar-brand{href: '/'}= application_name
          .collapse.navbar-collapse
            - if user_signed_in?
              %ul.nav.navbar-nav
                %li= link_to 'Saved Searches', saved_searches_path
                %li= link_to 'Your stories', my_stories_path
                %li= link_to 'All stories', hacker_news_stories_path
                - if current_user.admin?
                  %li= link_to 'Delayed Job', delayed_job_path, :'data-no-turbolink' => true
              %form.navbar-form.navbar-left{role: 'search', action: '/search'}
                .form-group
                  = text_field_tag :q, '', class: 'form-control', placeholder: 'Search'

              %p.navbar-text Signed in as #{current_user.email}
              %ul.nav.navbar-nav
                %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
            - else
              %ul.nav.navbar-nav
                %li= link_to 'Sign In', new_user_session_path
    .container-fluid
      .row
        .col-md-9.col-md-offset-1{role: 'main'}
          - flash.keys.each do |key|
            .alert{ class: "alert-#{rails_to_bootstrap_flash_key(key)}", role: 'alert' }
              %a.close{ href: '#', "data-dismiss" => "alert" } x
              %h4.alert-heading= key.capitalize
              - if flash[key].respond_to?(:each)
                - flash[key].each do |msg|
                  = msg
                  %br
              - else
                = flash[key]
              - flash.delete(key)
          = yield
  = yield(:page_javascript) if content_for? :page_javascript

app/views/saved_searches/_form.html.haml
= form_for saved_search do |f|
  - if saved_search.errors.any?
    #error_explanation
      %h2= "#{pluralize(saved_search.errors.count, "error")} prohibited this saved_search from being saved:"
      %ul
        - saved_search.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.text_field :query
    = f.submit 'Save'

app/views/saved_searches/index.html.haml
%h1 Your saved searches

%table.table
  %thead
    %tr
      %th Query
      %th


  %tbody
    - saved_searches.each do |saved_search|
      %tr
        %td= link_to saved_search.query, search_path(q: saved_search.query)
        %td= link_to 'Destroy', saved_search, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User search', new_saved_search_path

app/views/saved_searches/new.html.haml
%h1 New saved search

= render 'form', saved_search: saved_search

= link_to 'Back', saved_searches_path

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/